url: "https://www.pierrecunat.fr"
baseurl:
# "/GoToMountain/"

# Site settings
title: Pierre CUNAT <br> A. Guide de Haute Montagne
maintitle: Pierre CUNAT A. Guide Haute Montagne
email: pierre.cunat@gresille.org
description: "A. Guide de Haute Montagne, ski de randonn√©e, alpinisme, escalade, cascade de glace, dans les Hautes Alpes, le Massif des Ecrins et Oisans, Massif du Mont Blanc."


# Team names, titles and social links
people:
- name: Pierre CUNAT
  pic: 1
  position: Lead Designer
  social:
    - title: facebook
      url: https://www.facebook.com/pierrecunat

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-feed

include: ['_pages']

#Facebook Sharing
facebook_app_id: 1442363299439053
